name: CI
on:
  pull_request:
    paths:
      - "internal/**"

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.26.3'
          go-version-file: api/go.mod
          cache-dependency-path: api/go.sum
          cache: true
          architecture: 'x64'
